
LDAP_ENTRIES = {
    "delegues": [
        [{'givenName': ['Redacted'],
  'mail': ['email_redacted@epfl.ch'],
  'memberOf': ['Mini-Projet',
   'ce-ic',
   'delegues_ssc',
   'coaching15-16.ic',
   'lap_archord_2015',
   'delegues-classes'],
  'ou': ['SC-BA3',
   'Section de systèmes de communication - Bachelor semestre 3'],
  'sn': ['Benchekroun'],
  'uniqueIdentifier': ['251774']},
 {'givenName': ['Redacted'],
  'mail': ['email_redacted@epfl.ch'],
  'memberOf': ['Mini-Projet',
   'ce-ic',
   'coaching15-16.ic',
   'delegues-classes',
   'delegues_ssc',
   'lap_archord_2015'],
  'ou': ['AGEPINFO', 'AGEPoly - Equipe informatique'],
  'sn': ['Benchekroun'],
  'uniqueIdentifier': ['251774']}]
],
    "faculty_council": [],
    "epfl_assembly": [
        [{'givenName': ['Redacted'],
  'mail': ['email_redacted@epfl.ch'],
  'memberOf': ['AE-CandidatsElections2008',
   'AE-CandidatsElectionsAE-CF',
   'COlogin',
   'EnseignantsSMT',
   'IC-Calendar',
   'ICC2014-Enseignants',
   'Progmtel',
   'Recruiting',
   'cds',
   'corps-enseignant-epfl',
   'enseignants-epfl',
   'enseignants-ic',
   'grrbcom',
   'inbc',
   'infoscience-contacts-test',
   'prof',
   'respinfo-epfl',
   'sap-aim-epfl02',
   'tekhne',
   'testCO',
   'webmasters',
   'sre-epfl',
   'vpnguest-epfl',
   'EDPR_committee',
   'intranet-epfl',
   'personnel-epfl',
   'service-video',
   'studentproj',
   'iig_staff',
   'mer-epfl',
   'EDIC.IC-Faculty',
   'early-googleapps-adopter',
   'ICC-Enseignants',
   'EDIC.committee',
   'Lecturers.ic',
   'IC-Portal'],
  'ou': ['SCI-IC-RB', 'Groupe SCI IC RB'],
  'sn': ['Boulic'],
  'uniqueIdentifier': ['104608']},
 {'givenName': ['Redacted'],
  'mail': ['email_redacted@epfl.ch'],
  'memberOf': ['AE-CandidatsElections2008',
   'AE-CandidatsElectionsAE-CF',
   'COlogin',
   'EnseignantsSMT',
   'IC-Calendar',
   'ICC2014-Enseignants',
   'Progmtel',
   'Recruiting',
   'cds',
   'corps-enseignant-epfl',
   'enseignants-epfl',
   'enseignants-ic',
   'grrbcom',
   'inbc',
   'infoscience-contacts-test',
   'prof',
   'respinfo-epfl',
   'sap-aim-epfl02',
   'tekhne',
   'testCO',
   'webmasters',
   'sre-epfl',
   'vpnguest-epfl',
   'EDPR_committee',
   'intranet-epfl',
   'personnel-epfl',
   'service-video',
   'studentproj',
   'iig_staff',
   'mer-epfl',
   'EDIC.IC-Faculty',
   'early-googleapps-adopter',
   'ICC-Enseignants',
   'EDIC.committee',
   'Lecturers.ic',
   'IC-Portal'],
  'ou': ['SIN-ENS', 'SIN - Enseignement'],
  'sn': ['Boulic'],
  'uniqueIdentifier': ['104608']},
 {'givenName': ['Redacted'],
  'mail': ['email_redacted@epfl.ch'],
  'memberOf': ['AE-CandidatsElections2008',
   'AE-CandidatsElectionsAE-CF',
   'COlogin',
   'EnseignantsSMT',
   'IC-Calendar',
   'ICC2014-Enseignants',
   'Progmtel',
   'Recruiting',
   'cds',
   'corps-enseignant-epfl',
   'enseignants-epfl',
   'enseignants-ic',
   'grrbcom',
   'inbc',
   'infoscience-contacts-test',
   'prof',
   'respinfo-epfl',
   'sap-aim-epfl02',
   'tekhne',
   'testCO',
   'webmasters',
   'sre-epfl',
   'vpnguest-epfl',
   'EDPR_committee',
   'intranet-epfl',
   'personnel-epfl',
   'service-video',
   'studentproj',
   'iig_staff',
   'mer-epfl',
   'EDIC.IC-Faculty',
   'early-googleapps-adopter',
   'ICC-Enseignants',
   'EDIC.committee',
   'Lecturers.ic',
   'IC-Portal'],
  'ou': ['CF-IC', 'Conseil de faculté IC'],
  'sn': ['Boulic'],
  'uniqueIdentifier': ['104608']},
 {'givenName': ['Redacted'],
  'mail': ['email_redacted@epfl.ch'],
  'memberOf': ['AE-CandidatsElections2008',
   'AE-CandidatsElectionsAE-CF',
   'COlogin',
   'EDPR_committee',
   'EnseignantsSMT',
   'IC-Calendar',
   'ICC2014-Enseignants',
   'Progmtel',
   'Recruiting',
   'cds',
   'corps-enseignant-epfl',
   'enseignants-epfl',
   'enseignants-ic',
   'grrbcom',
   'iig_staff',
   'inbc',
   'infoscience-contacts-test',
   'intranet-epfl',
   'personnel-epfl',
   'prof',
   'respinfo-epfl',
   'sap-aim-epfl02',
   'service-video',
   'sre-epfl',
   'studentproj',
   'tekhne',
   'testCO',
   'vpnguest-epfl',
   'webmasters',
   'mer-epfl',
   'EDIC.IC-Faculty',
   'early-googleapps-adopter',
   'ICC-Enseignants',
   'EDIC.committee',
   'Lecturers.ic',
   'IC-Portal'],
  'ou': ['AE', "Assemblée d'Ecole"],
  'sn': ['Boulic'],
  }]
 ],
    "agepolitique": [
    [{'givenName': ['Redacted'],
  'mail': ['email_redacted@epfl.ch'],
  'memberOf': ['CS208_2014',
   'IC-Calendar',
   'Seminar-Crypto',
   'cms-assistants',
   'cs206-students',
   'group-cs208',
   'lap_archsoc_2015',
   'vvpc',
   'personnel-epfl',
   'agepoly_representation',
   'delegues-classes',
   'lap_archord_2015',
   'delegues_sin',
   'ictravel2016',
   'IC-Portal'],
  'ou': ['LACAL', 'Laboratoire de cryptologie algorithmique'],
  'sn': ['Boissaye'],
  'uniqueIdentifier': ['214939']},
 {'givenName': ['Redacted'],
  'mail': ['email_redacted@epfl.ch'],
  'memberOf': ['CS208_2014',
   'IC-Calendar',
   'Seminar-Crypto',
   'cms-assistants',
   'cs206-students',
   'group-cs208',
   'lap_archsoc_2015',
   'personnel-epfl',
   'vvpc',
   'agepoly_representation',
   'delegues-classes',
   'lap_archord_2015',
   'delegues_sin',
   'ictravel2016',
   'IC-Portal'],
  'ou': ['IN-BA5', "Section d'informatique - Bachelor semestre 5"],
  'sn': ['Boissaye'],
  'uniqueIdentifier': ['214939']},
 {'givenName': ['Redacted'],
  'mail': ['email_redacted@epfl.ch'],
  'memberOf': ['CS208_2014',
   'IC-Calendar',
   'Seminar-Crypto',
   'agepoly_representation',
   'cms-assistants',
   'cs206-students',
   'group-cs208',
   'lap_archsoc_2015',
   'personnel-epfl',
   'vvpc',
   'delegues-classes',
   'lap_archord_2015',
   'delegues_sin',
   'ictravel2016',
   'IC-Portal'],
  'ou': ['AGEPOLYTIQUE', 'AGEPoly - Equipe AGEPolytique'],
  'sn': ['Boissaye'],
  }]
],
    "comite": [
        [{'givenName': ['Redacted'],
  'mail': ['email_redacted@epfl.ch'],
  'memberOf': ['slackline', 'webmasters'],
  'ou': ['CHALLENGE', 'AGEPoly - Challenge'],
  'sn': ['Foucqueteau'],
  'uniqueIdentifier': ['215786']},
 {'givenName': ['Redacted'],
  'mail': ['email_redacted@epfl.ch'],
  'memberOf': ['slackline', 'webmasters'],
  'ou': ['AGEPOLY', "Association générale des étudiants de l'EPFL"],
  'sn': ['Foucqueteau'],
  'uniqueIdentifier': ['215786']},
 {'givenName': ['Redacted'],
  'mail': ['email_redacted@epfl.ch'],
  'memberOf': ['slackline', 'webmasters'],
  'ou': ['SC-MA1', 'Section de systèmes de communication - Master semestre 1'],
  'sn': ['Foucqueteau'],
  'uniqueIdentifier': ['215786']}]
],
    "agepinfo": [
        [{'givenName': ['Redacted'],
  'mail': ['email_redacted@epfl.ch'],
  'memberOf': ['CS422-students-2015',
   'EDO',
   'baric11-staff',
   'bigdata2015-AiiDA',
   'coaching.ic.2011',
   'googleTour_coachingIC',
   'plugdev',
   'souperfacIC2010',
   'souperracletteic2010',
   'sweng_students_2012',
   'weSkiCoachingIC1011'],
  'ou': ['IN-MA3', "Section d'informatique - Master semestre 3"],
  'sn': ['Boullier'],
  'uniqueIdentifier': ['205541']},
 {'givenName': ['Redacted'],
  'mail': ['email_redacted@epfl.ch'],
  'memberOf': ['CS422-students-2015',
   'EDO',
   'baric11-staff',
   'bigdata2015-AiiDA',
   'coaching.ic.2011',
   'googleTour_coachingIC',
   'plugdev',
   'souperfacIC2010',
   'souperracletteic2010',
   'sweng_students_2012',
   'weSkiCoachingIC1011'],
  'ou': ['AGEPINFO', 'AGEPoly - Equipe informatique'],
  'sn': ['Boullier'],
  'uniqueIdentifier': ['205541']}]
],
    "students": [
        [{'givenName': ['Redacted'],
  'mail': ['email_redacted@epfl.ch'],
  'memberOf': ['coaching15-16.ic'],
  'ou': ['IN-BA1', "Section d'informatique - Bachelor semestre 1"],
  'sn': ['Horn'],
  'uniqueIdentifier': ['245430']}]
    ]
}




